package view;

import dao.BillDAO;
import model.Bill;
import model.Client;
import model.Contract;
import model.Partner;
import model.PaymentDetail;
import model.User;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;

public class ConfirmFrm extends javax.swing.JFrame {

    private ContractFrm contractFrm;
    private Contract contract;
    private Bill bill;

    public ConfirmFrm() {
        initComponents();
        configureTable();
        setLocationRelativeTo(null);
    }

    public ConfirmFrm(Contract contract, Bill bill) {
        this(null, contract, bill);
    }

    public ConfirmFrm(ContractFrm contractFrm, Contract contract, Bill bill) {
        this.contractFrm = contractFrm;
        this.contract = contract;
        this.bill = bill;
        initComponents();
        configureTable();
        loadConfirmData();
        setSize(1180, 680);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblClientPhone = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblClientAddress = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblClientEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPartnerName = new javax.swing.JLabel();
        contractPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblContractInfo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblContractId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSignDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLoanTerm = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblRemainingDebt = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblCreator = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPaymentDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPaymentAmount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPaymentType = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        noteScrollPane = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        detailScrollPane = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xác nhận hóa đơn thanh toán");

        clientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách hàng"));
        clientPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Tên:");
        clientPanel.add(jLabel1);

        lblClientName.setText(" ");
        clientPanel.add(lblClientName);

        jLabel2.setText("SĐT:");
        clientPanel.add(jLabel2);

        lblClientPhone.setText(" ");
        clientPanel.add(lblClientPhone);

        jLabel3.setText("Địa chỉ:");
        clientPanel.add(jLabel3);

        lblClientAddress.setText(" ");
        clientPanel.add(lblClientAddress);

        jLabel4.setText("Email:");
        clientPanel.add(jLabel4);

        lblClientEmail.setText(" ");
        clientPanel.add(lblClientEmail);

        jLabel5.setText("Đối tác:");
        clientPanel.add(jLabel5);

        lblPartnerName.setText(" ");
        clientPanel.add(lblPartnerName);

        topPanel.add(clientPanel);

        contractPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hợp đồng"));
        contractPanel.setLayout(new java.awt.GridLayout(6, 2));

        jLabel6.setText("Thông tin:");
        contractPanel.add(jLabel6);

        lblContractInfo.setText(" ");
        contractPanel.add(lblContractInfo);

        jLabel7.setText("Mã HĐ:");
        contractPanel.add(jLabel7);

        lblContractId.setText(" ");
        contractPanel.add(lblContractId);

        jLabel8.setText("Ngày ký:");
        contractPanel.add(jLabel8);

        lblSignDate.setText(" ");
        contractPanel.add(lblSignDate);

        jLabel9.setText("Thời hạn:");
        contractPanel.add(jLabel9);

        lblLoanTerm.setText(" ");
        contractPanel.add(lblLoanTerm);

        jLabel10.setText("Tổng tiền:");
        contractPanel.add(jLabel10);

        lblTotalAmount.setText(" ");
        contractPanel.add(lblTotalAmount);

        jLabel11.setText("Dư nợ còn lại:");
        contractPanel.add(jLabel11);

        lblRemainingDebt.setText(" ");
        contractPanel.add(lblRemainingDebt);

        topPanel.add(contractPanel);

        paymentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));
        paymentPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel12.setText("Người tạo:");
        paymentPanel.add(jLabel12);

        lblCreator.setText(" ");
        paymentPanel.add(lblCreator);

        jLabel13.setText("Ngày thanh toán:");
        paymentPanel.add(jLabel13);

        lblPaymentDate.setText(" ");
        paymentPanel.add(lblPaymentDate);

        jLabel14.setText("Tổng tiền phải thanh toán:");
        paymentPanel.add(jLabel14);

        lblPaymentAmount.setText(" ");
        paymentPanel.add(lblPaymentAmount);

        jLabel15.setText("Phương thức:");
        paymentPanel.add(jLabel15);

        txtPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản" }));
        txtPaymentType.addActionListener(this::txtPaymentTypeActionPerformed);
        paymentPanel.add(txtPaymentType);

        jLabel16.setText("Ghi chú:");
        paymentPanel.add(jLabel16);

        txtNote.setColumns(20);
        txtNote.setRows(3);
        noteScrollPane.setViewportView(txtNote);

        paymentPanel.add(noteScrollPane);

        topPanel.add(paymentPanel);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(clientPanel, 0, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contractPanel, 0, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentPanel, 0, 0, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contractPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        detailScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin các đợt thanh toán lần này"));

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Đợt", "Hạn", "Số tiền thanh toán", "Còn lại sau thanh toán", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailScrollPane.setViewportView(tblDetails);

        btnSave.setText("Lưu");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addComponent(detailScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveBill();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentTypeActionPerformed

    private void configureTable() {
        tblDetails.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
    }

    private void loadConfirmData() {
        if (contract == null || bill == null) {
            return;
        }

        lblContractInfo.setText("Hợp đồng " + nullToBlank(contract.getId()));
        Client client = contract.getClient();
        Partner partner = contract.getPartner();
        lblClientName.setText(client == null ? "" : nullToBlank(client.getFullName()));
        lblClientPhone.setText(client == null ? "" : nullToBlank(client.getTel()));
        lblClientAddress.setText(client == null ? "" : nullToBlank(client.getAddress()));
        lblClientEmail.setText(client == null ? "" : nullToBlank(client.getEmail()));
        lblPartnerName.setText(partner == null ? "" : nullToBlank(partner.getPartnerName()));

        lblContractId.setText(nullToBlank(contract.getId()));
        lblSignDate.setText(ViewUtils.formatDate(contract.getSignDate()));
        lblLoanTerm.setText(contract.getLoanTerm() + " tháng");
        lblTotalAmount.setText(ViewUtils.formatMoney(contract.getTotalAmount()));
        lblRemainingDebt.setText(ViewUtils.formatMoney(contract.getTotalRemainingDebt()));

        User user = bill.getUser();
        lblCreator.setText(user == null ? "" : nullToBlank(user.getFullName()));
        lblPaymentDate.setText(ViewUtils.formatDate(LocalDate.now()));
        lblPaymentAmount.setText(ViewUtils.formatMoney(bill.getPaymentAmount()));

        reloadDetails();
    }

    private void reloadDetails() {
        DefaultTableModel tableModel = (DefaultTableModel) tblDetails.getModel();
        tableModel.setRowCount(0);
        for (PaymentDetail detail : bill.getPaymentDetails()) {
            tableModel.addRow(new Object[]{
                detail.getPaymentPeriod().getPeriod(),
                ViewUtils.formatDate(detail.getPaymentPeriod().getDueDate()),
                ViewUtils.formatMoney(detail.getAllocatedAmount()),
                ViewUtils.formatMoney(detail.getPaymentPeriod().getRemainingDebt()),
                detail.getNote()
            });
        }
    }

    private void saveBill() {
        if (bill == null || contract == null) {
            return;
        }

        String paymentType = txtPaymentType.getSelectedItem() == null ? "" : txtPaymentType.getSelectedItem().toString().trim();
        if (paymentType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phương thức thanh toán.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        bill.setPaymentDate(LocalDate.now());
        bill.setPaymentType(paymentType);
        bill.setNote(txtNote.getText().trim());
        updateDetailNotesFromTable();

        if (new BillDAO().addBill(bill)) {
            JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            contract.clearPendingPayments();
            if (contractFrm != null) {
                contractFrm.dispose();
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu hóa đơn thanh toán.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateDetailNotesFromTable() {
        if (tblDetails.isEditing()) {
            tblDetails.getCellEditor().stopCellEditing();
        }

        DefaultTableModel tableModel = (DefaultTableModel) tblDetails.getModel();
        int rowCount = Math.min(tableModel.getRowCount(), bill.getPaymentDetails().size());
        for (int row = 0; row < rowCount; row++) {
            Object noteValue = tableModel.getValueAt(row, 4);
            bill.getPaymentDetails().get(row).setNote(noteValue == null ? "" : noteValue.toString().trim());
        }
    }

    private String nullToBlank(String value) {
        return value == null ? "" : value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JPanel contractPanel;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblClientAddress;
    private javax.swing.JLabel lblClientEmail;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblClientPhone;
    private javax.swing.JLabel lblContractId;
    private javax.swing.JLabel lblContractInfo;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblLoanTerm;
    private javax.swing.JLabel lblPartnerName;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentDate;
    private javax.swing.JLabel lblRemainingDebt;
    private javax.swing.JLabel lblSignDate;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JScrollPane noteScrollPane;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JTable tblDetails;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JComboBox<String> txtPaymentType;
    // End of variables declaration//GEN-END:variables
}
