/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view;

import model.Bill;
import model.BoughtItem;
import model.Client;
import model.Contract;
import model.Item;
import model.Partner;
import model.PaymentPeriod;
import model.User;

/**
 *
 * @author Admin
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ContractFrm extends javax.swing.JFrame {

    private Contract contract;
    private Bill bill;

    public ContractFrm() {
        initComponents();
        configureTables();
        setLocationRelativeTo(null);
    }

    public ContractFrm(Contract contract, Bill bill) {
        this.contract = contract;
        this.bill = bill;
        initComponents();
        configureTables();
        reloadData();
        setTitle("Thông tin hợp đồng " + ViewUtils.blank(contract.getId()));
        setSize(1100, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClientFullName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblClientIdCard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblClientPhone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblClientAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblClientEmail = new javax.swing.JLabel();
        contractPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblContractUserName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblContractUserId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblContractUserPhone = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblContractUserEmail = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblContractUserAddress = new javax.swing.JLabel();
        partnerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblPartnerName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPartnerPhone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPartnerAddress = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPartnerEmail = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        itemScrollPane = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        periodScrollPane = new javax.swing.JScrollPane();
        tblPeriods = new javax.swing.JTable();
        lblPaymentHint = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        summaryPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblRemainingDebt = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblSummarySignDate = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblSummaryLoanTerm = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin hợp đồng");

        topPanel.setLayout(new java.awt.GridLayout(1, 3));

        clientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách hàng"));
        clientPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Họ tên:");
        clientPanel.add(jLabel1);

        lblClientFullName.setText(" ");
        clientPanel.add(lblClientFullName);

        jLabel2.setText("CCCD:");
        clientPanel.add(jLabel2);

        lblClientIdCard.setText(" ");
        clientPanel.add(lblClientIdCard);

        jLabel3.setText("SĐT:");
        clientPanel.add(jLabel3);

        lblClientPhone.setText(" ");
        clientPanel.add(lblClientPhone);

        jLabel4.setText("Địa chỉ:");
        clientPanel.add(jLabel4);

        lblClientAddress.setText(" ");
        clientPanel.add(lblClientAddress);

        jLabel5.setText("Email:");
        clientPanel.add(jLabel5);

        lblClientEmail.setText(" ");
        clientPanel.add(lblClientEmail);

        topPanel.add(clientPanel);

        contractPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Đại diện công ty"));
        contractPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel6.setText("Nhân viên kí:");
        contractPanel.add(jLabel6);

        lblContractUserName.setText(" ");
        contractPanel.add(lblContractUserName);

        jLabel7.setText("Mã nhân viên:");
        contractPanel.add(jLabel7);

        lblContractUserId.setText(" ");
        contractPanel.add(lblContractUserId);

        jLabel8.setText("Số điện thoại:");
        contractPanel.add(jLabel8);

        lblContractUserPhone.setText(" ");
        contractPanel.add(lblContractUserPhone);

        jLabel9.setText("Email:");
        contractPanel.add(jLabel9);

        lblContractUserEmail.setText(" ");
        contractPanel.add(lblContractUserEmail);

        jLabel10.setText("Địa chỉ:");
        contractPanel.add(jLabel10);

        lblContractUserAddress.setText(" ");
        contractPanel.add(lblContractUserAddress);

        topPanel.add(contractPanel);

        partnerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Đối tác"));
        partnerPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel11.setText("Công ty:");
        partnerPanel.add(jLabel11);

        lblPartnerName.setText(" ");
        partnerPanel.add(lblPartnerName);

        jLabel12.setText("SĐT:");
        partnerPanel.add(jLabel12);

        lblPartnerPhone.setText(" ");
        partnerPanel.add(lblPartnerPhone);

        jLabel13.setText("Địa chỉ:");
        partnerPanel.add(jLabel13);

        lblPartnerAddress.setText(" ");
        partnerPanel.add(lblPartnerAddress);

        jLabel14.setText("Email:");
        partnerPanel.add(jLabel14);

        lblPartnerEmail.setText(" ");
        partnerPanel.add(lblPartnerEmail);

        lblBankName.setText(" ");
        partnerPanel.add(lblBankName);

        topPanel.add(partnerPanel);

        itemScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách mặt hàng"));

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã MH", "Tên mặt hàng", "ĐVT", "Đơn giá", "SL", "Giảm giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemScrollPane.setViewportView(tblItems);
        if (tblItems.getColumnModel().getColumnCount() > 0) {
            tblItems.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        periodScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách đợt thanh toán"));

        tblPeriods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Đợt", "Hạn thanh toán", "Phải trả", "Đã trả", "Lãi quá hạn", "Thanh toán lần này", "Còn lại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeriods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodsMouseClicked(evt);
            }
        });
        periodScrollPane.setViewportView(tblPeriods);

        lblPaymentHint.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblPaymentHint.setText("Click vào đợt thanh toán để nhập số tiền thanh toán");

        summaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng hợp"));
        summaryPanel.setLayout(new java.awt.GridLayout(4, 2));

        jLabel16.setText("Tổng tiền hợp đồng:");
        summaryPanel.add(jLabel16);

        lblTotalAmount.setText(" ");
        summaryPanel.add(lblTotalAmount);

        jLabel17.setText("Tổng dư nợ còn lại:");
        summaryPanel.add(jLabel17);

        lblRemainingDebt.setText(" ");
        summaryPanel.add(lblRemainingDebt);

        jLabel18.setText("Ngày kí:");
        summaryPanel.add(jLabel18);

        lblSummarySignDate.setText(" ");
        summaryPanel.add(lblSummarySignDate);

        jLabel19.setText("Thời hạn vay:");
        summaryPanel.add(jLabel19);

        lblSummaryLoanTerm.setText(" ");
        summaryPanel.add(lblSummaryLoanTerm);

        btnNext.setText("Tiếp tục");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addComponent(summaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(summaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemScrollPane)
                    .addComponent(periodScrollPane)
                    .addComponent(lblPaymentHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaymentHint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPeriodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodsMouseClicked
        if (evt.getClickCount() == 1) {
            openSelectedPeriod();
        }
    }//GEN-LAST:event_tblPeriodsMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        confirmPayment();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void configureTables() {
        tblItems.setDefaultEditor(Object.class, null);
        tblPeriods.setDefaultEditor(Object.class, null);
    }

    public void reloadData() {
        if (contract == null) {
            return;
        }

        loadContractHeader();
        reloadItems();
        reloadPeriods();
        lblTotalAmount.setText(ViewUtils.formatMoney(contract.getTotalAmount()));
        lblRemainingDebt.setText(ViewUtils.formatMoney(contract.getTotalRemainingDebt()));
        lblSummarySignDate.setText(ViewUtils.formatDate(contract.getSignDate()));
        lblSummaryLoanTerm.setText(contract.getLoanTerm() + " tháng");
    }

    private void loadContractHeader() {
        Client client = contract.getClient();
        lblClientFullName.setText(client == null ? "" : ViewUtils.blank(client.getFullName()));
        lblClientIdCard.setText(client == null ? "" : ViewUtils.blank(client.getIdCard()));
        lblClientPhone.setText(client == null ? "" : ViewUtils.blank(client.getTel()));
        lblClientAddress.setText(client == null ? "" : ViewUtils.blank(client.getAddress()));
        lblClientEmail.setText(client == null ? "" : ViewUtils.blank(client.getEmail()));

        User contractUser = contract.getUser();
        lblContractUserName.setText(contractUser == null ? "" : ViewUtils.blank(contractUser.getFullName()));
        lblContractUserId.setText(contractUser == null ? "" : String.valueOf(contractUser.getId()));
        lblContractUserPhone.setText(contractUser == null ? "" : ViewUtils.blank(contractUser.getTel()));
        lblContractUserEmail.setText(contractUser == null ? "" : ViewUtils.blank(contractUser.getEmail()));
        lblContractUserAddress.setText(contractUser == null ? "" : ViewUtils.blank(contractUser.getAddress()));

        Partner partner = contract.getPartner();
        lblPartnerName.setText(partner == null ? "" : ViewUtils.blank(partner.getPartnerName()));
        lblPartnerPhone.setText(partner == null ? "" : ViewUtils.blank(partner.getPhoneNumber()));
        lblPartnerAddress.setText(partner == null ? "" : ViewUtils.blank(partner.getAddress()));
        lblPartnerEmail.setText(partner == null ? "" : ViewUtils.blank(partner.getEmail()));
    }

    private void reloadItems() {
        DefaultTableModel tableModel = (DefaultTableModel) tblItems.getModel();
        tableModel.setRowCount(0);
        int index = 1;
        for (BoughtItem boughtItem : contract.getBoughtItems()) {
            Item item = boughtItem.getItem();
            tableModel.addRow(new Object[]{
                index++,
                item == null ? "" : item.getId(),
                item == null ? "" : item.getName(),
                item == null ? "" : item.getUnit(),
                ViewUtils.formatMoney(boughtItem.getPrice()),
                boughtItem.getQuantity(),
                ViewUtils.formatMoney(boughtItem.getSellOff()),
                ViewUtils.formatMoney(boughtItem.getLineTotal())
            });
        }
    }

    private void reloadPeriods() {
        DefaultTableModel tableModel = (DefaultTableModel) tblPeriods.getModel();
        tableModel.setRowCount(0);
        for (PaymentPeriod period : contract.getPaymentPeriods()) {
            tableModel.addRow(new Object[]{
                period.getPeriod(),
                ViewUtils.formatDate(period.getDueDate()),
                ViewUtils.formatMoney(period.getPayableAmount()),
                ViewUtils.formatMoney(period.getPaidAmount()),
                ViewUtils.formatMoney(period.getOverdueInterest()),
                ViewUtils.formatMoney(period.getPendingPaymentAmount()),
                ViewUtils.formatMoney(period.getRemainingDebt()),
                period.getStatus()
            });
        }
    }

    private void openSelectedPeriod() {
        if (contract == null || bill == null) {
            return;
        }

        int row = tblPeriods.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đợt thanh toán.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PaymentPeriod period = contract.getPaymentPeriods().get(tblPeriods.convertRowIndexToModel(row));
        if (period.getRemainingDebt() <= 0 && period.getPendingPaymentAmount() <= 0) {
            JOptionPane.showMessageDialog(this, "Đợt này đã thanh toán đủ.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        new PaymentPeriodFrm(this, bill, period).setVisible(true);
    }

    private void confirmPayment() {
        if (bill == null || bill.getPaymentDetails().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thanh toán cho ít nhất một đợt.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        new ConfirmFrm(this, contract, bill).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JPanel contractPanel;
    private javax.swing.JScrollPane itemScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblClientAddress;
    private javax.swing.JLabel lblClientEmail;
    private javax.swing.JLabel lblClientFullName;
    private javax.swing.JLabel lblClientIdCard;
    private javax.swing.JLabel lblClientPhone;
    private javax.swing.JLabel lblContractUserAddress;
    private javax.swing.JLabel lblContractUserEmail;
    private javax.swing.JLabel lblContractUserId;
    private javax.swing.JLabel lblContractUserName;
    private javax.swing.JLabel lblContractUserPhone;
    private javax.swing.JLabel lblPartnerAddress;
    private javax.swing.JLabel lblPartnerEmail;
    private javax.swing.JLabel lblPartnerName;
    private javax.swing.JLabel lblPartnerPhone;
    private javax.swing.JLabel lblPaymentHint;
    private javax.swing.JLabel lblRemainingDebt;
    private javax.swing.JLabel lblSummaryLoanTerm;
    private javax.swing.JLabel lblSummarySignDate;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JPanel partnerPanel;
    private javax.swing.JScrollPane periodScrollPane;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblPeriods;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
