package view;

import dao.BillDAO;
import model.Bill;
import model.PaymentDetail;
import model.PaymentPeriod;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class PaymentPeriodFrm extends javax.swing.JFrame {

    private Bill bill;
    private PaymentPeriod period;
    private ContractFrm contractFrm;

    public PaymentPeriodFrm() {
        initComponents();
        configureTable();
        setLocationRelativeTo(null);
    }

    public PaymentPeriodFrm(Bill bill, PaymentPeriod period) {
        this(null, bill, period);
    }

    public PaymentPeriodFrm(ContractFrm contractFrm, Bill bill, PaymentPeriod period) {
        this.contractFrm = contractFrm;
        this.bill = bill;
        this.period = period;
        initComponents();
        configureTable();
        loadPaymentPeriod();
        setSize(700, 460);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPaymentPeriodInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPayableAmount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPaidAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOverdueInterest = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPendingAmount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRemainingDebt = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        historyScrollPane = new javax.swing.JScrollPane();
        tblPaymentDetail = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán đợt");

        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đợt thanh toán"));
        infoPanel.setLayout(new java.awt.GridLayout(7, 2, 6, 6));

        jLabel1.setText("Thông tin:");
        infoPanel.add(jLabel1);

        lblPaymentPeriodInfo.setText(" ");
        infoPanel.add(lblPaymentPeriodInfo);

        jLabel2.setText("Hạn thanh toán:");
        infoPanel.add(jLabel2);

        lblDueDate.setText(" ");
        infoPanel.add(lblDueDate);

        jLabel3.setText("Phải trả:");
        infoPanel.add(jLabel3);

        lblPayableAmount.setText(" ");
        infoPanel.add(lblPayableAmount);

        jLabel4.setText("Đã trả:");
        infoPanel.add(jLabel4);

        lblPaidAmount.setText(" ");
        infoPanel.add(lblPaidAmount);

        jLabel5.setText("Lãi quá hạn:");
        infoPanel.add(jLabel5);

        lblOverdueInterest.setText(" ");
        infoPanel.add(lblOverdueInterest);

        jLabel6.setText("Thanh toán lần này:");
        infoPanel.add(jLabel6);

        lblPendingAmount.setText(" ");
        infoPanel.add(lblPendingAmount);

        jLabel7.setText("Còn phải trả:");
        infoPanel.add(jLabel7);

        lblRemainingDebt.setText(" ");
        infoPanel.add(lblRemainingDebt);

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thanh toán lần này"));

        lblAmount.setText("Số tiền thanh toán:");

        txtAmount.setColumns(18);
        txtAmount.addActionListener(this::txtAmountActionPerformed);

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        historyScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch sử thanh toán"));

        tblPaymentDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Ngày", "Số tiền", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyScrollPane.setViewportView(tblPaymentDetail);

        btnNext.setText("Xác nhận");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        savePaymentAmount();
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        savePaymentAmount();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void configureTable() {
        tblPaymentDetail.setDefaultEditor(Object.class, null);
    }

    private void loadPaymentPeriod() {
        if (period == null) {
            return;
        }

        setTitle("Thanh toán đợt " + period.getPeriod());
        lblPaymentPeriodInfo.setText("Mã đợt " + nullToBlank(period.getId()) + " - Đợt " + period.getPeriod());
        lblDueDate.setText(ViewUtils.formatDate(period.getDueDate()));
        lblPayableAmount.setText(ViewUtils.formatMoney(period.getPayableAmount()));
        lblPaidAmount.setText(ViewUtils.formatMoney(period.getPaidAmount()));
        lblOverdueInterest.setText(ViewUtils.formatMoney(period.getOverdueInterest()));
        lblPendingAmount.setText(ViewUtils.formatMoney(period.getPendingPaymentAmount()));
        lblRemainingDebt.setText(ViewUtils.formatMoney(period.getRemainingDebt()));

        if (period.getPendingPaymentAmount() > 0) {
            txtAmount.setText(ViewUtils.formatRawMoney(period.getPendingPaymentAmount()));
        }

        reloadHistory();
    }

    private void reloadHistory() {
        DefaultTableModel tableModel = (DefaultTableModel) tblPaymentDetail.getModel();
        tableModel.setRowCount(0);

        ArrayList<PaymentDetail> details = new BillDAO().searchPaymentDetailInBill(period);
        for (PaymentDetail detail : details) {
            tableModel.addRow(new Object[]{
                    detail.getId(),
                    ViewUtils.formatDate(detail.getPaymentDate()),
                    ViewUtils.formatMoney(detail.getAllocatedAmount()),
                    detail.getNote()
            });
        }
    }

    private void savePaymentAmount() {
        if (bill == null || period == null) {
            return;
        }

        String rawAmount = txtAmount.getText();
        if (rawAmount.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền thanh toán.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double amount;
        try {
            amount = ViewUtils.parseMoney(rawAmount);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số tiền thanh toán phải là số.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Số tiền thanh toán phải lớn hơn 0.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double maxAmount = period.getRemainingDebt() + period.getPendingPaymentAmount();
        if (amount > maxAmount) {
            JOptionPane.showMessageDialog(this, "Số tiền thanh toán không được vượt quá " + ViewUtils.formatMoney(maxAmount) + ".", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        bill.setPaymentDetail(period, amount, "");

        if (contractFrm != null) {
            contractFrm.reloadData();
        }
        dispose();
    }

    private String nullToBlank(String value) {
        return value == null ? "" : value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane historyScrollPane;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblOverdueInterest;
    private javax.swing.JLabel lblPaidAmount;
    private javax.swing.JLabel lblPayableAmount;
    private javax.swing.JLabel lblPaymentPeriodInfo;
    private javax.swing.JLabel lblPendingAmount;
    private javax.swing.JLabel lblRemainingDebt;
    private javax.swing.JTable tblPaymentDetail;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
