package view;

import model.User;

public class SellerHomeFrm extends javax.swing.JFrame {

    private User user;

    public SellerHomeFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public SellerHomeFrm(User user) {
        this.user = user;
        initComponents();
        loadUserData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        btnMakePayment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ nhân viên hành chính");

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        mainPanel.setLayout(new java.awt.GridLayout(6, 2, 8, 8));

        jLabel1.setText("Mã nhân viên:");
        mainPanel.add(jLabel1);

        lblUserId.setText(" ");
        mainPanel.add(lblUserId);

        jLabel2.setText("Họ tên:");
        mainPanel.add(jLabel2);

        lblFullName.setText(" ");
        mainPanel.add(lblFullName);

        jLabel3.setText("Địa chỉ:");
        mainPanel.add(jLabel3);

        lblAddress.setText(" ");
        mainPanel.add(lblAddress);

        jLabel4.setText("Số điện thoại:");
        mainPanel.add(jLabel4);

        lblPhone.setText(" ");
        mainPanel.add(lblPhone);

        jLabel5.setText("Email:");
        mainPanel.add(jLabel5);

        lblEmail.setText(" ");
        mainPanel.add(lblEmail);

        jLabel6.setText("Chức vụ:");
        mainPanel.add(jLabel6);

        lblPosition.setText(" ");
        mainPanel.add(lblPosition);

        btnMakePayment.setText("Thanh toán");
        btnMakePayment.addActionListener(this::btnMakePaymentActionPerformed);

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMakePayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnMakePayment))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        new SearchContractFrm(user).setVisible(true);
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginFrm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void loadUserData() {
        if (user == null) {
            return;
        }

        lblUserId.setText(String.valueOf(user.getId()));
        lblFullName.setText(nullToBlank(user.getFullName()));
        lblAddress.setText(nullToBlank(user.getAddress()));
        lblPhone.setText(nullToBlank(user.getTel()));
        lblEmail.setText(nullToBlank(user.getEmail()));
        lblPosition.setText(nullToBlank(user.getPosition()));
    }

    private String nullToBlank(String value) {
        return value == null ? "" : value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
